function contentChecks(ids=[],name='linkedContent'){
  const selectedIds=new Set(ids||[]);
  if(!state.contents.length)return '<div class="notice">Aucun contenu dans la bibliothèque.</div>';
  return `<div class="check-grid">${state.contents.map(c=>`<label class="check"><input type="checkbox" name="${name}" value="${c.id}" ${selectedIds.has(c.id)?'checked':''}><span><strong>${icon(c.type)} ${esc(c.name)}</strong><br><span class="muted">${esc(c.type)}</span></span></label>`).join('')}</div>`;
}

function renderInlineContentCreator(targetId,onCreated){
  const target=document.getElementById(targetId);if(!target)return;
  target.innerHTML=`<div class="card" style="margin-top:12px;border-left:5px solid var(--accent)"><div class="form-grid"><label class="field"><span>Type</span><select data-f="type"><option>PDF</option><option>Audio</option><option>Texte</option><option>Vidéo</option><option>Image</option><option>Lien</option></select></label><label class="field"><span>Titre</span><input data-f="title"></label><label class="field"><span>Visible pour</span><select data-f="group">${groupOptions()}</select></label><label class="field full"><span>Description</span><textarea data-f="desc"></textarea></label></div><div data-f="source" style="margin-top:12px"></div><div class="actions" style="margin-top:12px"><button class="btn primary" data-a="save">Ajouter</button><button class="btn" data-a="cancel">Annuler</button></div></div>`;
  const type=target.querySelector('[data-f=type]'),source=target.querySelector('[data-f=source]');
  const draw=()=>{const t=type.value;if(t==='PDF')source.innerHTML='<label class="field"><span>Fichier PDF</span><input data-f="file" type="file" accept="application/pdf,.pdf"></label><label class="field"><span>Image d’illustration</span><input data-f="cover" type="file" accept="image/*"></label>';else if(t==='Audio')source.innerHTML='<label class="field"><span>Source</span><select data-f="sourceType"><option value="file">Fichier audio</option><option value="url">Lien audio</option></select></label><div data-f="dynamic"></div><label class="field"><span>Image d’illustration</span><input data-f="cover" type="file" accept="image/*"></label>';else if(t==='Texte')source.innerHTML='<label class="field"><span>Source</span><select data-f="sourceType"><option value="text">Texte</option><option value="file">Document</option><option value="url">Lien</option></select></label><div data-f="dynamic"></div><label class="field"><span>Image d’illustration</span><input data-f="cover" type="file" accept="image/*"></label>';else if(t==='Vidéo')source.innerHTML='<label class="field"><span>Lien vidéo</span><input data-f="url" type="url"></label><label class="field"><span>Image d’illustration</span><input data-f="cover" type="file" accept="image/*"></label>';else if(t==='Image')source.innerHTML='<label class="field"><span>Fichier image</span><input data-f="file" type="file" accept="image/*"></label>';else source.innerHTML='<label class="field"><span>Lien</span><input data-f="url" type="url"></label><label class="field"><span>Image d’illustration</span><input data-f="cover" type="file" accept="image/*"></label>';
    const st=source.querySelector('[data-f=sourceType]');if(st){const dynamic=source.querySelector('[data-f=dynamic]');const drawDyn=()=>{dynamic.innerHTML=st.value==='file'?`<label class="field"><span>Fichier</span><input data-f="file" type="file" ${t==='Audio'?'accept="audio/*,.mp3,.m4a,.wav,.ogg"':'accept="text/*,.txt,.pdf,.doc,.docx"'}></label>`:st.value==='url'?'<label class="field"><span>Lien</span><input data-f="url" type="url"></label>':'<label class="field"><span>Texte</span><textarea data-f="text"></textarea></label>'};st.onchange=drawDyn;drawDyn();}
  };
  type.onchange=draw;draw();
  target.querySelector('[data-a=cancel]').onclick=()=>target.innerHTML='';
  target.querySelector('[data-a=save]').onclick=async()=>{
    const t=type.value,title=target.querySelector('[data-f=title]').value.trim();if(!title)return toast('Indiquez un titre');
    const audioKind=t==='Audio'?target.querySelector('[data-audio-kind=inline]')?.value:'';if(t==='Audio'&&!audioKind)return toast('Choisissez Chant audio ou Audio parlé');const id=Date.now(),item={id,name:title,type:t,category:t==='Audio'?audioKind:(TYPE_CATEGORY[t]||t),audioKind:t==='Audio'?(audioKind==='Chants audio'?'chant':'spoken'):'',audience:target.querySelector('[data-f=group]').value,description:target.querySelector('[data-f=desc]').value,sourceType:'',url:'',text:'',fileName:'',hasCover:false};
    ensureCategory(item.category);
    const st=source.querySelector('[data-f=sourceType]')?.value;
    if(t==='Vidéo'||t==='Lien'||st==='url'){const u=source.querySelector('[data-f=url]')?.value.trim();if(!u)return toast('Indiquez un lien');item.sourceType='url';item.url=u;}
    else if(t==='Texte'&&st==='text'){const tx=source.querySelector('[data-f=text]')?.value.trim();if(!tx)return toast('Saisissez le texte');item.sourceType='text';item.text=tx;}
    else {const file=source.querySelector('[data-f=file]')?.files[0];if(!file)return toast('Choisissez un fichier');if(t==='PDF'&&file.type!=='application/pdf'&&!file.name.toLowerCase().endsWith('.pdf'))return toast('Le fichier doit être un PDF');if(t==='Audio'&&!file.type.startsWith('audio/'))return toast('Le fichier doit être un audio');if(t==='Image'&&!file.type.startsWith('image/'))return toast('Le fichier doit être une image');item.sourceType='file';item.fileName=file.name;await putMedia(id,file);}
    const cover=source.querySelector('[data-f=cover]')?.files[0];if(cover){if(!cover.type.startsWith('image/'))return toast('L’illustration doit être une image');await putMedia('cover-'+id,cover);item.hasCover=true;item.coverFileName=cover.name;}
    state.contents.push(item);saveState(state);target.innerHTML='';onCreated(id);toast('Contenu ajouté');
  };
}

editDay=function(key){
  const c=selected(),d=c.days.find(x=>x.key===key);if(!d)return renderProgram();
  const events=state.events.filter(e=>e.celebrationId===c.id&&e.dayKey===key).sort((a,b)=>(a.time||'99:99').localeCompare(b.time||'99:99'));
  panel.innerHTML=`${context()}<div class="card"><div class="eyebrow">Jour</div><h2>${esc(d.label)}</h2><div class="form-grid"><label class="field"><span>Nom du jour</span><input id="dLabel" value="${esc(d.label)}"></label><label class="field"><span>Date de début</span><input id="dStart" type="date" value="${esc(d.startDate||'')}"></label><label class="field"><span>Date de fin</span><input id="dEnd" type="date" value="${esc(d.endDate||'')}"></label><label class="field full"><span>Texte du jour</span><textarea id="dText">${esc(d.text||'')}</textarea></label></div><h3>Liens</h3><div id="dayLinks">${(d.links||[]).map((l,i)=>linkRow(l,i)).join('')}</div><button class="btn small" id="addLink">+ Ajouter un lien</button><h3>Contenus du jour</h3>${contentChecks(d.contentIds||[],'dayContent')}<div class="actions" style="margin-top:10px"><button class="btn small" id="createDayContent">+ Créer un contenu</button></div><div id="dayInlineContent"></div><div class="actions" style="margin-top:18px"><button class="btn primary" id="saveDay">Enregistrer le jour</button><button class="btn" onclick="renderProgram()">Retour</button></div></div><div class="card section"><div class="section-head"><h2 style="margin:0">Rendez-vous</h2><button class="btn primary" onclick="showDayEventForm('${key}')">+ Ajouter un rendez-vous</button></div><div id="dayEventForm"></div><div class="list">${events.length?events.map(eventRow).join(''):'<div class="notice">Aucun rendez-vous.</div>'}</div></div>`;
  addLink.onclick=()=>dayLinks.insertAdjacentHTML('beforeend',linkRow({label:'',url:''},dayLinks.children.length));
  createDayContent.onclick=()=>renderInlineContentCreator('dayInlineContent',id=>{d.contentIds=[...(d.contentIds||[]),id];saveState(state);editDay(key)});
  saveDay.onclick=()=>{const s=dStart.value,e=dEnd.value||s;if(s&&e&&e<s)return toast('La date de fin doit suivre la date de début');d.label=dLabel.value.trim()||d.label;d.startDate=s;d.endDate=e;d.text=dText.value;d.links=[...dayLinks.querySelectorAll('[data-link-row]')].map(r=>({label:r.querySelector('[data-link-label]').value.trim(),url:r.querySelector('[data-link-url]').value.trim()})).filter(x=>x.url);d.contentIds=[...document.querySelectorAll('input[name=dayContent]:checked')].map(x=>+x.value);saveState(state);editDay(key);toast('Jour enregistré')};
};

showDayEventForm=function(dayKey,eventId=null){
  const c=selected(),e=eventId?state.events.find(x=>x.id===eventId):null,target=document.getElementById('dayEventForm');if(!target)return;
  target.innerHTML=`<div class="notice" style="margin-bottom:14px"><div class="form-grid"><label class="field"><span>Heure</span><input id="evtTime" type="time" value="${esc(e?.time||'')}"></label><label class="field"><span>Visible pour</span><select id="evtGroup">${groupOptions(e?.audience||'all')}</select></label><label class="field full"><span>Titre</span><input id="evtTitle" value="${esc(e?.title||'')}"></label><label class="field full"><span>Description</span><textarea id="evtDesc">${esc(e?.description||'')}</textarea></label></div><h4>Contenus associés</h4>${contentChecks(e?.contentIds||[],'evtContent')}<div class="actions" style="margin-top:10px"><button class="btn small" id="createEventContent">+ Créer un contenu</button></div><div id="eventInlineContent"></div><div class="actions" style="margin-top:14px"><button class="btn primary" id="saveEventBtn">${e?'Enregistrer':'Ajouter'}</button><button class="btn" onclick="document.getElementById('dayEventForm').innerHTML=''">Annuler</button></div></div>`;
  createEventContent.onclick=()=>renderInlineContentCreator('eventInlineContent',id=>{const ids=[...document.querySelectorAll('input[name=evtContent]:checked')].map(x=>+x.value);ids.push(id);const data={celebrationId:c.id,dayKey,time:evtTime.value,title:evtTitle.value.trim()||'Rendez-vous',audience:evtGroup.value,description:evtDesc.value,contentIds:[...new Set(ids)]};if(e)Object.assign(e,data);else {const ne={id:Date.now()+1,...data};state.events.push(ne);}saveState(state);editDay(dayKey)});
  saveEventBtn.onclick=()=>{const title=evtTitle.value.trim();if(!title)return toast('Indiquez un titre');const data={celebrationId:c.id,dayKey,time:evtTime.value,title,audience:evtGroup.value,description:evtDesc.value,contentIds:[...document.querySelectorAll('input[name=evtContent]:checked')].map(x=>+x.value)};if(e)Object.assign(e,data);else state.events.push({id:Date.now(),...data});saveState(state);editDay(dayKey)};
};

const oldRenderMedia=renderMedia;
renderMedia=function(){
  oldRenderMedia();
  document.querySelectorAll('.admin-row').forEach(row=>{});
  const list=[...document.querySelectorAll('#panel .card.section .admin-row')];
  list.forEach((row,i)=>{const c=state.contents[i];if(!c)return;const actions=row.querySelector('.row-actions')||document.createElement('div');if(!actions.classList.contains('row-actions')){actions.className='row-actions';const del=row.querySelector('.btn.danger');if(del){del.remove();actions.appendChild(del);}row.appendChild(actions);}const b=document.createElement('button');b.className='btn';b.textContent='Modifier';b.onclick=()=>editContent(c.id);actions.insertBefore(b,actions.firstChild);});
};

function editContent(id){
  const c=state.contents.find(x=>x.id===id);if(!c)return renderMedia();
  panel.innerHTML=`<div class="card"><h2>Modifier le contenu</h2><div class="form-grid"><label class="field full"><span>Titre</span><input id="ecTitle" value="${esc(c.name)}"></label><label class="field"><span>Type</span><input value="${esc(c.type)}" disabled></label><label class="field"><span>Visible pour</span><select id="ecGroup">${groupOptions(c.audience||'all')}</select></label><label class="field full"><span>Description</span><textarea id="ecDesc">${esc(c.description||'')}</textarea></label>${c.url?`<label class="field full"><span>Lien</span><input id="ecUrl" type="url" value="${esc(c.url)}"></label>`:''}${c.type==='Texte'&&c.sourceType==='text'?`<label class="field full"><span>Texte</span><textarea id="ecText">${esc(c.text||'')}</textarea></label>`:''}</div><div class="actions" style="margin-top:14px"><button class="btn primary" id="saveContentEdit">Enregistrer</button><button class="btn" onclick="renderMedia()">Retour</button></div></div>`;
  saveContentEdit.onclick=()=>{c.name=ecTitle.value.trim()||c.name;c.audience=ecGroup.value;c.description=ecDesc.value;if(document.getElementById('ecUrl'))c.url=ecUrl.value.trim();if(document.getElementById('ecText'))c.text=ecText.value;saveState(state);renderMedia();toast('Contenu modifié')};
}

renderCategories=function(){panel.innerHTML=`<div class="card"><h2>Catégories</h2><div class="searchbar"><input id="newCategory"><button class="btn primary" id="addCategory">Ajouter</button></div><div class="list">${state.categories.map((c,i)=>`<div class="admin-row"><strong>${esc(c)}</strong><div class="row-actions"><button class="btn" onclick="renameCategory(${i})">Modifier</button><button class="btn danger" onclick="removeCategory('${c.replace(/'/g,"\\'")}')">Supprimer</button></div></div>`).join('')}</div></div>`;addCategory.onclick=()=>{const v=newCategory.value.trim();if(!v)return;if(state.categories.includes(v))return toast('Cette catégorie existe déjà');state.categories.push(v);saveState(state);renderCategories()}};
function renameCategory(i){const old=state.categories[i],v=prompt('Nom de la catégorie',old)?.trim();if(!v||v===old)return;state.categories[i]=v;state.contents.forEach(c=>{if(c.category===old)c.category=v});saveState(state);renderCategories()}

renderGroups=function(){panel.innerHTML=`<div class="card"><h2>Groupes</h2><div class="searchbar"><input id="newGroup"><button class="btn primary" id="addGroup">Ajouter</button></div><div class="list">${state.groups.map(g=>`<div class="admin-row"><strong>${esc(g.name)}</strong><div class="row-actions">${g.id!=='all'?`<button class="btn" onclick="renameGroup('${esc(g.id)}')">Modifier</button><button class="btn danger" onclick="removeGroup('${esc(g.id)}')">Supprimer</button>`:'<span class="badge">Tous</span>'}</div></div>`).join('')}</div></div>`;addGroup.onclick=()=>{const n=newGroup.value.trim();if(!n)return;state.groups.push({id:'group-'+Date.now(),name:n});saveState(state);renderGroups()}};
function renameGroup(id){const g=state.groups.find(x=>x.id===id);if(!g)return;const v=prompt('Nom du groupe',g.name)?.trim();if(!v)return;g.name=v;saveState(state);renderGroups()}

render();