const CELEBRATIONS_SUPABASE_URL='https://jwyayfkssyagvnablttg.supabase.co';
const CELEBRATIONS_SUPABASE_KEY='sb_publishable_qm8yJyH_5LfP-oZ1sz4QLg_r9J5VdnA';
const CELEBRATIONS_MEDIA_BUCKET='celebrations-media';
const sbHeaders=(extra={})=>({apikey:CELEBRATIONS_SUPABASE_KEY,'Content-Type':'application/json',...extra});
const smartId=v=>/^\d+$/.test(String(v??''))?Number(v):String(v??'');
async function sbJson(path,options={}){const r=await fetch(CELEBRATIONS_SUPABASE_URL+path,{...options,headers:sbHeaders(options.headers||{})});if(!r.ok)throw new Error((await r.text())||`Supabase ${r.status}`);const t=await r.text();return t?JSON.parse(t):null}
async function loadStateFromSupabase(){
 const [celebrations,steps,events,contents,eventContents,stepContents,links,groups]=await Promise.all([sbJson('/rest/v1/celebrations_celebrations?select=*&order=id'),sbJson('/rest/v1/celebrations_steps?select=*&order=sort_order'),sbJson('/rest/v1/celebrations_events?select=*&order=sort_order'),sbJson('/rest/v1/celebrations_contents?select=*&order=created_at'),sbJson('/rest/v1/celebrations_event_contents?select=*&order=sort_order'),sbJson('/rest/v1/celebrations_step_contents?select=*&order=sort_order'),sbJson('/rest/v1/celebrations_links?select=*&order=sort_order'),sbJson('/rest/v1/celebrations_groups?select=*&order=sort_order')]);
 const ecs=new Map(),scs=new Map();eventContents.forEach(x=>{const k=String(x.event_id);if(!ecs.has(k))ecs.set(k,[]);ecs.get(k).push(smartId(x.content_id))});stepContents.forEach(x=>{const k=`${x.celebration_id}|${x.step_key}`;if(!scs.has(k))scs.set(k,[]);scs.get(k).push(smartId(x.content_id))});
 const byCel=new Map();steps.forEach(x=>{if(!byCel.has(Number(x.celebration_id)))byCel.set(Number(x.celebration_id),[]);byCel.get(Number(x.celebration_id)).push({key:x.step_key,label:x.label,startDate:x.start_date||'',endDate:x.end_date||'',text:x.body_text||'',links:[],contentIds:scs.get(`${x.celebration_id}|${x.step_key}`)||[]})});links.forEach(l=>{if(l.event_id)return;const d=(byCel.get(Number(l.celebration_id))||[]).find(x=>x.key===l.step_key);if(d)d.links.push({label:l.label||'',url:l.url,kind:l.link_type||'link'})});
 const cels=celebrations.map(c=>({id:Number(c.id),archangel:c.archangel,year:c.year||'',status:c.status||'planned',days:byCel.get(Number(c.id))||[]}));const cont=contents.map(c=>({id:smartId(c.id),name:c.name,type:c.content_type,category:c.category||'',audience:c.audience||'all',description:c.description||'',sourceType:c.source_type||'',url:c.external_url||'',text:c.inline_text||'',fileName:c.file_name||'',mimeType:c.mime_type||'',storagePath:c.storage_path||'',hasCover:!!c.has_cover,coverStoragePath:c.cover_storage_path||'',coverFileName:c.cover_file_name||'',audioKind:c.audio_kind||''}));const ev=events.map(e=>({id:smartId(e.id),celebrationId:Number(e.celebration_id),dayKey:e.step_key,title:e.title,time:e.event_time||'',description:e.description||'',audience:e.audience||'all',sortOrder:Number(e.sort_order??0),contentIds:ecs.get(String(e.id))||[],links:links.filter(l=>String(l.event_id||'')===String(e.id)).map(l=>({label:l.label||'',url:l.url,kind:l.link_type||'link'}))}));const active=cels.find(c=>c.status==='active')||cels[0];return {version:7,currentCelebrationId:active?.id||null,adminCelebrationId:active?.id||cels[0]?.id||null,profile:localStorage.getItem('celebrations-public-profile-chosen')||'all',groups:groups.length?groups.map(g=>({id:g.id,name:g.name})):clone(DEFAULTS.groups),categories:[...new Set(cont.map(c=>c.category).filter(Boolean))],celebrations:cels,contents:cont,events:ev};
}
function supabaseMediaUrl(path){if(!path)return '';const value=String(path);if(value.startsWith('data:')||/^https?:\/\//i.test(value))return value;return `${CELEBRATIONS_SUPABASE_URL}/storage/v1/object/public/${CELEBRATIONS_MEDIA_BUCKET}/${value.split('/').map(encodeURIComponent).join('/')}`}
async function getMedia(key){const s=typeof state!=='undefined'?state:null;const c=s?.contents?.find(x=>String(x.id)===String(key).replace(/^cover-/,''));if(!c)return null;const path=String(key).startsWith('cover-')?c.coverStoragePath:c.storagePath;if(!path)return null;const r=await fetch(supabaseMediaUrl(path),{headers:{apikey:CELEBRATIONS_SUPABASE_KEY}});return r.ok?await r.blob():null}
function escPreviewText(v){return String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
async function openStoredFile(content){
 const path=content?.storagePath;if(!path)return alert('Fichier indisponible.');
 const directUrl=supabaseMediaUrl(path),declaredMime=String(content?.mimeType||'').toLowerCase(),isPdf=content?.type==='PDF'||declaredMime==='application/pdf'||/\.pdf(?:$|[?#])/i.test(String(content?.fileName||path));
 if(isPdf){window.open(directUrl,'_blank','noopener');return}
 const popup=window.open('about:blank','_blank');
 try{const r=await fetch(directUrl);if(!r.ok)throw new Error('Fichier indisponible');const b=await r.blob();const mime=(content.mimeType||b.type||'').toLowerCase();const u=URL.createObjectURL(new Blob([b],{type:mime||'application/octet-stream'}));if(!popup){URL.revokeObjectURL(u);return alert('Autorisez les fenêtres contextuelles pour ouvrir ce contenu.')}const title=escPreviewText(content.name||content.fileName||'Contenu');const fileName=escPreviewText(content.fileName||content.name||'fichier');const download=`<a href="${u}" download="${fileName}" style="position:fixed;right:14px;top:12px;z-index:5;padding:9px 13px;border-radius:8px;background:#fff;color:#111;text-decoration:none;font:600 14px system-ui;box-shadow:0 2px 10px #0004">Télécharger</a>`;const body=mime.startsWith('image/')?`${download}<img src="${u}" alt="${title}" style="display:block;max-width:100%;max-height:100vh;margin:auto;object-fit:contain">`:mime.startsWith('audio/')?`<div style="min-height:100vh;display:grid;place-items:center;padding:24px">${download}<div style="width:min(720px,100%)"><h1 style="font:600 22px system-ui;margin:0 0 18px">${title}</h1><audio controls src="${u}" style="width:100%"></audio></div></div>`:mime.startsWith('video/')?`${download}<video controls src="${u}" style="display:block;width:100%;height:100vh;object-fit:contain;background:#000"></video>`:`${download}<iframe src="${u}" title="${title}" style="width:100%;height:100vh;border:0"></iframe>`;popup.document.open();popup.document.write(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><style>html,body{margin:0;min-height:100%;background:#111;color:#fff}body{font-family:system-ui,sans-serif}</style></head><body>${body}</body></html>`);popup.document.close();popup.addEventListener('beforeunload',()=>URL.revokeObjectURL(u),{once:true});setTimeout(()=>URL.revokeObjectURL(u),30*60*1000)}catch(e){if(popup)popup.close();alert('Impossible d’ouvrir ce contenu.')}
}
async function attachAudioPlayer(container,content){const path=content?.storagePath;if(!path){container.innerHTML='<span class="muted">Fichier audio indisponible.</span>';return}const row=document.createElement('div');row.style.cssText='display:flex;align-items:center;gap:10px;width:100%;flex-wrap:wrap';const a=document.createElement('audio');a.controls=true;a.preload='metadata';a.src=supabaseMediaUrl(path);a.style.cssText='flex:1 1 280px;min-width:0';const label=document.createElement('label');label.style.cssText='display:inline-flex;align-items:center;gap:5px;white-space:nowrap;font:600 13px system-ui,sans-serif;cursor:pointer';const checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.setAttribute('aria-label','Lecture en boucle');checkbox.addEventListener('change',()=>{a.loop=checkbox.checked});label.append(checkbox,document.createTextNode('En boucle'));row.append(a);const skip=document.createElement('div');skip.className='audio-skip-controls';skip.style.cssText='display:flex;gap:8px;align-items:center;width:100%;justify-content:center';const skipButton=(text,seconds,aria)=>{const b=document.createElement('button');b.type='button';b.textContent=text;b.setAttribute('aria-label',aria);b.className='audio-skip-button';b.style.cssText='display:inline-flex!important;align-items:center;justify-content:center;min-width:92px;min-height:42px;border:1px solid #94a3b8;border-radius:10px;background:#fff;color:#111;padding:9px 14px;font:700 15px system-ui,sans-serif;cursor:pointer';b.addEventListener('click',()=>{const duration=Number.isFinite(a.duration)?a.duration:Infinity;a.currentTime=Math.max(0,Math.min(duration,a.currentTime+seconds))});return b};skip.append(skipButton('−10 s',-10,'Reculer de 10 secondes'),skipButton('+10 s',10,'Avancer de 10 secondes'));row.append(skip);if(String(content?.audioKind||'').toLowerCase()!=='spoken'&&content?.category!=='Audios parlés')row.append(label);container.appendChild(row)}